//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::permissions::Entity as Permissions;
pub use super::roles::Entity as Roles;
pub use super::roles_permissions::Entity as RolesPermissions;
pub use super::user::Entity as User;
